// src/facts.js
// Base de données de 200+ anecdotes hors ligne, toutes vérifiées

export const FACTS = [
  // ── SCIENCE ────────────────────────────────────────────────
  { id: 1,  cat: "science",  text: "Les pieuvres ont trois cœurs : deux pompent le sang vers les branchies, un seul vers le reste du corps — et il s'arrête à chaque fois qu'elles nagent." },
  { id: 2,  cat: "science",  text: "Un éclair atteint 30 000 °C, soit cinq fois la température de la surface du Soleil." },
  { id: 3,  cat: "science",  text: "L'ADN humain déroulé d'une seule cellule mesure environ 2 mètres ; celui de toutes tes cellules réunies ferait 150 fois l'aller-retour Terre-Soleil." },
  { id: 4,  cat: "science",  text: "Les fourmis peuvent soulever jusqu'à 50 fois leur propre poids, soit l'équivalent pour un humain de soulever une voiture." },
  { id: 5,  cat: "science",  text: "La vitesse de la lumière est si grande qu'elle pourrait faire 7,5 tours de la Terre en une seule seconde." },
  { id: 6,  cat: "science",  text: "Le cerveau humain génère assez d'électricité pour alimenter une ampoule de 25 watts." },
  { id: 7,  cat: "science",  text: "Les os humains sont, à volume égal, quatre fois plus résistants que le béton armé." },
  { id: 8,  cat: "science",  text: "Un nuage d'orage ordinaire pèse en moyenne 500 000 tonnes — l'équivalent de 80 000 éléphants." },
  { id: 9,  cat: "science",  text: "La banane est légèrement radioactive en raison de sa teneur en potassium-40, un isotope naturel." },
  { id: 10, cat: "science",  text: "Le son voyage 4 fois plus vite dans l'eau que dans l'air, c'est pourquoi les baleines peuvent communiquer sur des milliers de kilomètres." },
  { id: 11, cat: "science",  text: "Il faut environ 8 minutes et 20 secondes à la lumière du Soleil pour atteindre la Terre." },
  { id: 12, cat: "science",  text: "Le corps humain contient suffisamment de fer pour fabriquer un clou de 3 centimètres." },
  { id: 13, cat: "science",  text: "Les requins existent depuis 450 millions d'années, soit bien avant les dinosaures et même avant les arbres." },
  { id: 14, cat: "science",  text: "La crevette-mante frappe sa proie avec la force d'une balle de pistolet, générant une onde de choc qui assomme ou tue instantanément." },
  { id: 15, cat: "science",  text: "Saturne est la seule planète du système solaire dont la densité est inférieure à celle de l'eau — elle flotterait si un océan assez grand existait." },

  // ── HISTOIRE ───────────────────────────────────────────────
  { id: 16, cat: "histoire", text: "Cléopâtre a vécu plus près de l'invention de l'iPhone que de la construction des pyramides de Gizeh." },
  { id: 17, cat: "histoire", text: "La guerre de Cent Ans a en réalité duré 116 ans, de 1337 à 1453." },
  { id: 18, cat: "histoire", text: "Napoléon n'était pas particulièrement petit : il mesurait 1,69 m, taille tout à fait normale pour l'époque." },
  { id: 19, cat: "histoire", text: "Les vikings naviguaient sans boussole grâce à la « pierre solaire », un cristal d'spath d'Islande permettant de localiser le soleil même par temps couvert." },
  { id: 20, cat: "histoire", text: "Oxford University est plus ancienne que les Aztèques : l'université a été fondée vers 1096, l'empire aztèque vers 1300." },
  { id: 21, cat: "histoire", text: "La France est le seul pays à avoir exécuté une reine par guillotine : Marie-Antoinette en 1793." },
  { id: 22, cat: "histoire", text: "Jules César était épileptique et souffrait très probablement de migraines chroniques selon les historiens modernes." },
  { id: 23, cat: "histoire", text: "Les anciens Romains utilisaient de l'urine comme dentifrice et comme lessive — l'ammoniaque qu'elle contient est un excellent détachant." },
  { id: 24, cat: "histoire", text: "Le sapin de Noël comme tradition est apparu en Allemagne au XVIe siècle, popularisé en France par la reine Marie-Antoinette d'origine autrichienne." },
  { id: 25, cat: "histoire", text: "La première photographie de l'histoire, prise par Nicéphore Niépce en 1826, a nécessité une exposition de huit heures." },
  { id: 26, cat: "histoire", text: "Charlemagne ne savait pas lire mais gardait une ardoise sous son oreiller pour s'entraîner à tracer des lettres avant de dormir." },
  { id: 27, cat: "histoire", text: "La Seconde Guerre mondiale s'est officiellement terminée le 2 septembre 1945, mais le Japon et la Russie n'ont signé un traité de paix qu'en… 2022." },
  { id: 28, cat: "histoire", text: "Alexandre le Grand était tellement admiré qu'à sa mort, son corps ne montra aucun signe de décomposition pendant six jours — probablement parce qu'il était en état de mort clinique, pas encore décédé." },
  { id: 29, cat: "histoire", text: "La peste noire du XIVe siècle a tué entre 30 et 60 % de la population européenne, soit entre 25 et 50 millions de personnes." },
  { id: 30, cat: "histoire", text: "Le premier réseau de chemin de fer passager au monde a été inauguré en Angleterre en 1825, reliant Stockton à Darlington." },

  // ── GÉOGRAPHIE ─────────────────────────────────────────────
  { id: 31, cat: "geo",      text: "La Russie est si vaste qu'elle couvre 11 fuseaux horaires différents, soit près d'un tiers de la circumférence terrestre." },
  { id: 32, cat: "geo",      text: "Le Canada possède la plus longue côte maritime du monde avec 202 080 km — soit plus de 5 fois le tour de la Terre." },
  { id: 33, cat: "geo",      text: "La France est le pays le plus visité au monde avec environ 100 millions de touristes par an." },
  { id: 34, cat: "geo",      text: "L'Australie est plus large que la Lune : 4 000 km contre 3 474 km de diamètre lunaire." },
  { id: 35, cat: "geo",      text: "La mer Caspienne est le plus grand lac du monde, mais on l'appelle « mer » car son eau est salée." },
  { id: 36, cat: "geo",      text: "Le Nil et l'Amazone se disputent le titre de fleuve le plus long : selon les mesures, l'un ou l'autre peut remporter le titre." },
  { id: 37, cat: "geo",      text: "Le mont Everest grandit d'environ 4 mm par an en raison de la pression tectonique entre les plaques indienne et eurasienne." },
  { id: 38, cat: "geo",      text: "La ville la plus froide du monde habitée est Oïmiakon en Sibérie, où la température a atteint -71,2 °C en 1924." },
  { id: 39, cat: "geo",      text: "Le Vatican est le seul État au monde à ne pas avoir de citoyens nés sur son territoire — on y naît pas, on y est nommé." },
  { id: 40, cat: "geo",      text: "La Méditerranée s'est complètement asséchée il y a 5,96 millions d'années lors de la « crise messinienne »." },
  { id: 41, cat: "geo",      text: "Plus de la moitié de la population mondiale vit dans un cercle qui tient dans l'Asie du Sud-Est, entre l'Inde et la Chine." },
  { id: 42, cat: "geo",      text: "Les Alpes Suisses contiennent suffisamment de réserves d'eau douce dans leurs glaciers pour alimenter l'Europe pendant des décennies." },
  { id: 43, cat: "geo",      text: "Le Sahara n'est pas toujours désertique : il y a 6 000 ans, il était vert, avec des lacs, des rivières et une faune abondante." },
  { id: 44, cat: "geo",      text: "La ville de Venise s'enfonce d'environ 2 mm par an dans la lagune, et a déjà baissé de 25 cm depuis le XXe siècle." },
  { id: 45, cat: "geo",      text: "L'île de Nouvelle-Zélande est l'un des derniers endroits de la planète à avoir été colonisés par des humains, vers 1280 ap. J.-C." },

  // ── ART & CULTURE ──────────────────────────────────────────
  { id: 46, cat: "art",      text: "La Joconde ne possède ni cils ni sourcils — c'était la mode à Florence au XVe siècle de les épiler entièrement." },
  { id: 47, cat: "art",      text: "Beethoven a composé la plupart de ses chefs-d'œuvre après être devenu complètement sourd, dont la Neuvième Symphonie." },
  { id: 48, cat: "art",      text: "Shakespeare a inventé plus de 1 700 mots anglais encore utilisés aujourd'hui, dont « bedroom », « lonely » et « generous »." },
  { id: 49, cat: "art",      text: "La Tour Eiffel est repeinte toutes les 7 ans et il faut 60 tonnes de peinture pour la couvrir entièrement." },
  { id: 50, cat: "art",      text: "Le tableau le plus cher jamais vendu est « Salvator Mundi » attribué à Léonard de Vinci, adjugé 450 millions de dollars en 2017." },
  { id: 51, cat: "art",      text: "Le Louvre est le musée le plus visité du monde avec environ 9 millions de visiteurs par an." },
  { id: 52, cat: "art",      text: "Mozart a composé sa première symphonie à l'âge de 8 ans et son premier opéra à 11 ans." },
  { id: 53, cat: "art",      text: "La célèbre fresque de la Chapelle Sixtine a pris 4 ans à Michel-Ange, de 1508 à 1512, allongé sur des échafaudages." },
  { id: 54, cat: "art",      text: "Le premier roman de l'histoire est considéré être « Le Dit du Genji » écrit par une dame de cour japonaise vers l'an 1000." },
  { id: 55, cat: "art",      text: "Pablo Picasso a peint plus de 20 000 œuvres au cours de sa vie, soit plus d'une par jour en moyenne." },
  { id: 56, cat: "art",      text: "L'Opéra de Sydney a été conçu par un architecte danois, Jørn Utzon, qui n'a jamais vu le bâtiment terminé — il est parti avant la fin des travaux." },
  { id: 57, cat: "art",      text: "Le roman « Guerre et Paix » de Tolstoï comporte 580 personnages et a été révisé sept fois par son auteur." },
  { id: 58, cat: "art",      text: "La Vénus de Milo a perdu ses bras avant d'être découverte — on ne sait toujours pas ce qu'elle tenait dans ses mains." },
  { id: 59, cat: "art",      text: "Les Grecs de l'Antiquité peignaient leurs statues en couleurs vives ; ce que nous voyons en blanc aujourd'hui est l'effet du temps qui a effacé les pigments." },
  { id: 60, cat: "art",      text: "Le célèbre « Cri » d'Edvard Munch n'est pas un cri de peur mais d'angoisse face à un coucher de soleil rouge sang qu'il vit à Oslo." },

  // ── TECHNOLOGIE ────────────────────────────────────────────
  { id: 61, cat: "tech",     text: "Le premier message envoyé sur ARPANET (ancêtre d'Internet) en 1969 était \"lo\" — le réseau planta avant la fin du mot « login »." },
  { id: 62, cat: "tech",     text: "Le premier ordinateur pesait 27 tonnes et occupait une surface de 167 m², soit la taille d'un appartement." },
  { id: 63, cat: "tech",     text: "Un iPhone modern contient plus de puissance de calcul que tous les ordinateurs utilisés par la NASA lors de la mission Apollo 11." },
  { id: 64, cat: "tech",     text: "Le premier SMS de l'histoire a été envoyé le 3 décembre 1992 : « Merry Christmas » par l'ingénieur Neil Papworth." },
  { id: 65, cat: "tech",     text: "Google traite plus de 8,5 milliards de recherches par jour, soit environ 100 000 chaque seconde." },
  { id: 66, cat: "tech",     text: "Le nom « bug » informatique vient d'un vrai insecte : en 1947, une mite s'est coincée dans un relais du Harvard Mark II, causant une panne." },
  { id: 67, cat: "tech",     text: "La première souris d'ordinateur était en bois, inventée par Doug Engelbart en 1964, et n'avait qu'un seul bouton." },
  { id: 68, cat: "tech",     text: "YouTube consomme plus de 1 million de gigaoctets de données par jour — soit l'équivalent de 250 000 films HD." },
  { id: 69, cat: "tech",     text: "Le code source de la page Wikipedia en français contient plus de texte que l'Encyclopédie de Diderot et d'Alembert en entier." },
  { id: 70, cat: "tech",     text: "Le premier domaine internet (.com) jamais enregistré est symbolics.com, le 15 mars 1985." },
  { id: 71, cat: "tech",     text: "Amazon a commencé comme simple librairie en ligne depuis le garage de Jeff Bezos à Bellevue, Washington, en 1994." },
  { id: 72, cat: "tech",     text: "La quantité de données créées chaque jour dans le monde dépasse 2,5 quintillions d'octets, un chiffre à 19 zéros." },
  { id: 73, cat: "tech",     text: "Le Wi-Fi a été accidentellement inventé grâce à des recherches sur les trous noirs — la technologie de suppression d'écho vient de l'astronomie." },
  { id: 74, cat: "tech",     text: "Les câbles sous-marins transportent plus de 95 % du trafic internet mondial ; les satellites ne gèrent qu'une infime partie." },
  { id: 75, cat: "tech",     text: "Le premier jeu vidéo commercial, Pong, a été développé par Atari en 1972 avec un budget de seulement 75 dollars." },

  // ── NATURE ─────────────────────────────────────────────────
  { id: 76, cat: "nature",   text: "Un seul arbre mature peut absorber jusqu'à 22 kg de CO₂ par an et produire suffisamment d'oxygène pour deux personnes." },
  { id: 77, cat: "nature",   text: "Les dauphins dorment avec un seul hémisphère cérébral à la fois pour rester vigilants et ne pas se noyer." },
  { id: 78, cat: "nature",   text: "Le miel est le seul aliment qui ne se périme jamais : du miel vieux de 3 000 ans trouvé dans des tombes égyptiennes était encore comestible." },
  { id: 79, cat: "nature",   text: "Un groupe de flamants roses s'appelle une « flamboyance », un groupe de chouettes une « parlement »." },
  { id: 80, cat: "nature",   text: "Les éléphants sont les seuls animaux capables de reconnaître leurs morts et d'exprimer quelque chose qui ressemble au deuil." },
  { id: 81, cat: "nature",   text: "Une seule colonie de chauves-souris peut consommer 500 tonnes d'insectes par nuit, jouant un rôle crucial dans l'équilibre écologique." },
  { id: 82, cat: "nature",   text: "Le baobab peut stocker jusqu'à 120 000 litres d'eau dans son tronc, lui permettant de survivre aux longues sécheresses africaines." },
  { id: 83, cat: "nature",   text: "Les coraux sont à la fois des animaux, des végétaux (via leurs algues symbiotiques) et des minéraux — une relation unique dans la nature." },
  { id: 84, cat: "nature",   text: "La pieuvre géante du Pacifique peut changer couleur, texture et forme en moins d'une seconde pour se camoufler parfaitement." },
  { id: 85, cat: "nature",   text: "Les arbres d'une forêt communiquent entre eux via un réseau de champignons souterrains surnommé le « Wood Wide Web »." },
  { id: 86, cat: "nature",   text: "Un hectare de forêt tropicale peut abriter jusqu'à 300 espèces d'arbres différentes — autant que toute l'Europe tempérée réunie." },
  { id: 87, cat: "nature",   text: "Le tardigrade, minuscule animal de 0,5 mm, peut survivre dans le vide de l'espace, à des températures de -272 °C et résister à des radiations létales." },
  { id: 88, cat: "nature",   text: "Les pieuvres ont un cerveau dans chacun de leurs huit tentacules — soit 9 cerveaux au total." },
  { id: 89, cat: "nature",   text: "Le ver de terre améliore tellement les sols qu'un hectare de bonne terre agricole en contient jusqu'à 2 millions." },
  { id: 90, cat: "nature",   text: "Les manchots empereurs peuvent plonger jusqu'à 500 mètres de profondeur et retenir leur souffle pendant 20 minutes." },

  // ── SCIENCE suite ──────────────────────────────────────────
  { id: 91,  cat: "science",  text: "Les neurones du cerveau humain transmettent des signaux à une vitesse pouvant atteindre 431 km/h." },
  { id: 92,  cat: "science",  text: "Le corps humain est composé à 99 % de vide — les atomes eux-mêmes sont presque entièrement composés d'espace vide." },
  { id: 93,  cat: "science",  text: "La lumière solaire qui nous éclaire aujourd'hui a en réalité quitté le noyau du Soleil il y a... 100 000 ans." },
  { id: 94,  cat: "science",  text: "Il y a plus de combinaisons possibles dans un jeu de 52 cartes qu'il n'y a d'atomes dans notre galaxie." },
  { id: 95,  cat: "science",  text: "La masse de tous les insectes sur Terre est environ 17 fois supérieure à la masse de tous les humains réunis." },
  { id: 96,  cat: "science",  text: "La glace est moins dense que l'eau liquide — c'est pourquoi elle flotte, ce qui permet aux écosystèmes aquatiques de survivre en hiver." },
  { id: 97,  cat: "science",  text: "La durée d'un jour sur Vénus est plus longue que sa propre année — elle tourne si lentement sur elle-même." },
  { id: 98,  cat: "science",  text: "Les chats ne peuvent pas percevoir le goût sucré — ils manquent d'un récepteur gustatif spécifique aux sucrés." },
  { id: 99,  cat: "science",  text: "Le corps humain produit environ 25 millions de nouvelles cellules par seconde pour remplacer celles qui meurent." },
  { id: 100, cat: "science",  text: "La vitesse à laquelle l'herbe pousse, cumulée sur tous les gazons du monde, est plus rapide que celle à laquelle les humains la tondent." },

  // ── HISTOIRE suite ─────────────────────────────────────────
  { id: 101, cat: "histoire", text: "L'égyptienne Hatchepsout a régné déguisée en pharaon masculin pendant 20 ans, portant barbe postiche et vêtements d'homme." },
  { id: 102, cat: "histoire", text: "Les Romains utilisaient les urines de chat pour blanchir les vêtements — l'ammoniac qu'elles contiennent dissout les taches." },
  { id: 103, cat: "histoire", text: "La Grande Muraille de Chine a été construite sur plus de 2 000 ans par des millions d'ouvriers, dont beaucoup sont enterrés dans ses fondations." },
  { id: 104, cat: "histoire", text: "Le pain de mie tranché industriellement fut commercialisé pour la première fois en 1928, considéré comme « la plus grande innovation depuis le pain en lui-même »." },
  { id: 105, cat: "histoire", text: "Le duel entre Alexander Hamilton et Aaron Burr en 1804 a tué le premier secrétaire du Trésor américain — fondateur du système financier des États-Unis." },
  { id: 106, cat: "histoire", text: "Les gladiateurs romains ne combattaient pas toujours à mort : les spectateurs votaient pour épargner le perdant valeureux." },
  { id: 107, cat: "histoire", text: "Galilée est mort la même année que Newton est né — 1642 — comme si la physique se transmettait d'un génie à l'autre." },
  { id: 108, cat: "histoire", text: "L'Empire ottoman a duré 623 ans, de 1299 à 1922, bien plus longtemps que l'Empire romain d'Occident." },
  { id: 109, cat: "histoire", text: "Marie Curie est la seule personne à avoir reçu deux prix Nobel dans deux disciplines différentes : physique et chimie." },
  { id: 110, cat: "histoire", text: "Le titre « césar » ou « tsar » vient directement du nom Julius Caesar, transmis pendant 2 000 ans à travers les empires." },

  // ── GÉO suite ──────────────────────────────────────────────
  { id: 111, cat: "geo",      text: "Le point le plus profond de l'océan, la fosse des Mariannes, est plus profond que l'Everest est haut — 11 km contre 8,8 km." },
  { id: 112, cat: "geo",      text: "Il existe une ville nommée « A » en Norvège et une nommée « B » en Autriche — les noms les plus courts au monde." },
  { id: 113, cat: "geo",      text: "La Finlande compte plus de 188 000 lacs, soit plus que tout autre pays du monde par rapport à sa superficie." },
  { id: 114, cat: "geo",      text: "La France possède des territoires sur 5 continents, faisant d'elle le pays avec le deuxième plus grand domaine maritime du monde." },
  { id: 115, cat: "geo",      text: "Le désert de Gobi grandit de 3 300 km² par an, grignotant les terres agricoles de Chine à un rythme alarmant." },
  { id: 116, cat: "geo",      text: "L'Islande est l'un des rares endroits au monde où l'on peut voir à l'œil nu la frontière entre deux plaques tectoniques." },
  { id: 117, cat: "geo",      text: "La ville de Singapour est un État à elle seule, plus petite que Paris et sa banlieue, mais avec un PIB supérieur à beaucoup de pays." },
  { id: 118, cat: "geo",      text: "Les îles Maldives sont l'archipel le plus plat du monde avec une altitude maximale de seulement 2,4 mètres — très vulnérable à la montée des eaux." },
  { id: 119, cat: "geo",      text: "Le fleuve Amazone déverse dans l'Atlantique 20 % de toute l'eau douce que les fleuves du monde entier déversent dans les océans." },
  { id: 120, cat: "geo",      text: "L'Antarctique est techniquement le plus grand désert du monde — il reçoit moins de 200 mm de précipitations par an." },

  // ── ART suite ──────────────────────────────────────────────
  { id: 121, cat: "art",      text: "Le bleu « Klein » est un bleu si intense qu'il fut breveté par l'artiste Yves Klein en 1960 — une couleur déposée légalement." },
  { id: 122, cat: "art",      text: "Vincent van Gogh n'a vendu qu'un seul tableau de son vivant, « La Vigne rouge », pour 400 francs — aujourd'hui ses œuvres valent des centaines de millions." },
  { id: 123, cat: "art",      text: "L'Iliade d'Homère comporte 15 693 vers et fut d'abord transmise oralement pendant des siècles avant d'être écrite." },
  { id: 124, cat: "art",      text: "La cathédrale Notre-Dame de Paris a mis 182 ans à être construite, de 1163 à 1345." },
  { id: 125, cat: "art",      text: "Le Taj Mahal a été construit par l'empereur moghol Shah Jahan en hommage à sa femme décédée — 20 000 ouvriers y ont travaillé pendant 22 ans." },
  { id: 126, cat: "art",      text: "Le jazz est né à La Nouvelle-Orléans vers 1900, fusion de blues, gospel, ragtime et musiques africaines — première grande musique vraiment américaine." },
  { id: 127, cat: "art",      text: "L'acteur le plus payé de l'histoire du cinéma muet était Charlie Chaplin, qui gagnait l'équivalent de 50 millions de dollars actuels par an." },
  { id: 128, cat: "art",      text: "La première bande dessinée de l'histoire est « The Yellow Kid » de R.F. Outcault, publiée en 1895 dans un journal de New York." },
  { id: 129, cat: "art",      text: "Versailles comptait 20 000 chandelles pour ses grandes soirées, nécessitant 150 valets uniquement pour les allumer et les entretenir." },
  { id: 130, cat: "art",      text: "La langue française utilisée dans les pièces de Molière est plus proche du français moderne que le Shakespeare de l'anglais contemporain." },

  // ── TECH suite ─────────────────────────────────────────────
  { id: 131, cat: "tech",     text: "Le GPS a été développé par l'armée américaine et ouvert au public par Ronald Reagan en 1983 après qu'un avion civil coréen fut abattu par erreur." },
  { id: 132, cat: "tech",     text: "La première caméra numérique, inventée par Steve Sasson chez Kodak en 1975, pesait 3,6 kg et produisait des images en noir et blanc de 100x100 pixels." },
  { id: 133, cat: "tech",     text: "Le protocole TCP/IP qui fait fonctionner Internet a été conçu pour résister à une attaque nucléaire en créant un réseau sans point central." },
  { id: 134, cat: "tech",     text: "Il existe plus de téléphones mobiles actifs que de personnes sur Terre — environ 8,5 milliards d'abonnements pour 8 milliards d'humains." },
  { id: 135, cat: "tech",     text: "Le premier vol commercial d'un avion de ligne date de 1914 : un hydravion reliant St. Petersburg à Tampa en Floride, en 23 minutes." },
  { id: 136, cat: "tech",     text: "Le code source du premier système d'exploitation UNIX tenait sur une seule feuille A4 imprimée — aujourd'hui Linux en compte des millions de lignes." },
  { id: 137, cat: "tech",     text: "L'électricité voyageant dans un câble de cuivre se déplace à environ 70 % de la vitesse de la lumière." },
  { id: 138, cat: "tech",     text: "La batterie lithium-ion qui équipe vos smartphones a été inventée par John Goodenough, qui a reçu le Nobel de chimie à 97 ans en 2019." },
  { id: 139, cat: "tech",     text: "SpaceX a réussi à faire atterrir et réutiliser des fusées, divisant par 10 le coût d'accès à l'espace par rapport aux années 2000." },
  { id: 140, cat: "tech",     text: "Le premier email de l'histoire a été envoyé par Ray Tomlinson en 1971 — il ne se souvient plus de ce qu'il a écrit, probablement « QWERTYUIOP »." },

  // ── NATURE suite ───────────────────────────────────────────
  { id: 141, cat: "nature",   text: "Les girafes dorment seulement 30 minutes par jour en plusieurs courtes siestes — leur long cou les rend vulnérables à se relever rapidement." },
  { id: 142, cat: "nature",   text: "Le champignon Armillaria ostoyae en Oregon occupe 9 km² et a plus de 8 000 ans — c'est le plus grand organisme vivant connu." },
  { id: 143, cat: "nature",   text: "Les étoiles de mer n'ont pas de cerveau ni de sang — elles utilisent de l'eau de mer pour transporter les nutriments dans leur corps." },
  { id: 144, cat: "nature",   text: "Le pistachier est l'un des arbres les plus lents au monde : il lui faut 15 à 20 ans pour produire ses premières noix." },
  { id: 145, cat: "nature",   text: "Les chimpanzés et les humains partagent 98,7 % de leur ADN — ils sont plus proches de nous que des gorilles." },
  { id: 146, cat: "nature",   text: "Un seul vol de sauterelles du criquet pèlerin peut contenir 80 millions d'individus et consommer en un jour la nourriture de 35 000 personnes." },
  { id: 147, cat: "nature",   text: "La baleine bleue est l'animal le plus grand ayant jamais existé sur Terre — plus grand que n'importe quel dinosaure." },
  { id: 148, cat: "nature",   text: "Les fourmis légionnaires construisent des ponts vivants avec leurs corps pour franchir des obstacles, coordination sans chef ni plan." },
  { id: 149, cat: "nature",   text: "Le colibri est le seul oiseau capable de voler à reculons, grâce à ses ailes battant 80 fois par seconde." },
  { id: 150, cat: "nature",   text: "Le venin du cone snail marin est si puissant qu'il peut tuer un humain en quelques heures, et il n'existe pas d'antidote." },

  // ── Bonus round ────────────────────────────────────────────
  { id: 151, cat: "science",  text: "Les abeilles peuvent reconnaître les visages humains et s'en souvenir grâce à une technique similaire à la reconnaissance faciale humaine." },
  { id: 152, cat: "histoire", text: "La première femme à avoir obtenu un doctorat universitaire au monde était Elena Cornaro Piscopia, à Padoue en 1678." },
  { id: 153, cat: "geo",      text: "Le plus petit pays du monde, le Vatican, avec 0,44 km², a pourtant son propre code postal, sa monnaie, sa radio et son équipe de football." },
  { id: 154, cat: "art",      text: "La harpe est l'un des instruments les plus anciens : des représentations vieilles de 5 000 ans ont été trouvées en Mésopotamie." },
  { id: 155, cat: "tech",     text: "Le premier robot industriel, Unimate, fut installé chez General Motors en 1961 pour souder des pièces — sans jamais se plaindre ni demander d'augmentation." },
  { id: 156, cat: "nature",   text: "Les cactus ne sont pas des plantes du désert à l'origine — ils viennent des forêts tropicales et se sont adaptés à la sécheresse au fil des siècles." },
  { id: 157, cat: "science",  text: "Il y a plus d'étoiles dans l'univers observable que de grains de sable sur toutes les plages et déserts de la Terre." },
  { id: 158, cat: "histoire", text: "La première loi sur le droit d'auteur fut adoptée en Angleterre en 1710, protégeant les auteurs pour une durée de… 14 ans renouvelables." },
  { id: 159, cat: "geo",      text: "L'Inde dépasse la Chine en population depuis 2023, devenant officiellement le pays le plus peuplé du monde." },
  { id: 160, cat: "art",      text: "Le mot « robot » vient du tchèque « robota » signifiant travail forcé ou corvée, inventé par l'écrivain Karel Čapek en 1920." },
  { id: 161, cat: "tech",     text: "Le premier satellite artificiel, Spoutnik 1, pesait 83,6 kg et n'émettait qu'un simple bip radio — mais il changea l'histoire de l'humanité." },
  { id: 162, cat: "nature",   text: "La langue d'un caméléon peut s'étendre en 0,07 seconde pour capturer une proie, soit deux fois plus vite qu'un clignement d'œil humain." },
  { id: 163, cat: "science",  text: "Le gaz que tu inhales aujourd'hui contient statistiquement des molécules d'oxygène qu'a respirées Jules César, Cléopâtre ou Napoléon." },
  { id: 164, cat: "histoire", text: "Ada Lovelace, fille de Lord Byron, a écrit le premier algorithme informatique en 1843 — un siècle avant l'invention des ordinateurs." },
  { id: 165, cat: "geo",      text: "La Bolivie possède deux capitales : Sucre (constitutionnelle) et La Paz (administrative) — un compromis unique au monde issu d'une guerre civile." },
  { id: 166, cat: "art",      text: "Le film « Blanche-Neige et les Sept Nains » de Disney en 1937 fut le premier long-métrage animé de l'histoire du cinéma." },
  { id: 167, cat: "tech",     text: "La quantité d'énergie solaire frappant la Terre en une heure suffirait à alimenter toute l'humanité pendant une année entière." },
  { id: 168, cat: "nature",   text: "Un éléphant reconnaît son reflet dans un miroir — une capacité partagée avec seulement les humains, grands singes, dauphins et corbeaux." },
  { id: 169, cat: "science",  text: "L'eau chaude peut geler plus vite que l'eau froide dans certaines conditions — c'est l'effet Mpemba, connu depuis Aristote mais encore mal expliqué." },
  { id: 170, cat: "histoire", text: "Le champagne a été inventé par accident : les bulles étaient considérées comme un défaut de fabrication jusqu'au XVIIe siècle." },
  { id: 171, cat: "geo",      text: "La ville de Tokyo est la plus grande agglomération urbaine du monde avec plus de 37 millions d'habitants." },
  { id: 172, cat: "art",      text: "La Sagrada Família de Barcelone, entamée en 1882, sera le plus long chantier cathédral de l'histoire à son achèvement prévu en 2026." },
  { id: 173, cat: "tech",     text: "Le microprocesseur Intel 4004 de 1971 contenait 2 300 transistors ; un chip moderne en contient plus de 100 milliards." },
  { id: 174, cat: "nature",   text: "Les arbres de séquoia géant peuvent vivre plus de 3 000 ans et atteindre 115 mètres de hauteur — les plus grands êtres vivants en volume." },
  { id: 175, cat: "science",  text: "La gravité déforme le temps : une horloge au sommet d'une montagne avance légèrement plus vite qu'une horloge au niveau de la mer." },
  { id: 176, cat: "histoire", text: "Le premier zoo public de l'histoire a ouvert à Vienne en 1752 — le zoo de Schönbrunn, qui existe encore aujourd'hui." },
  { id: 177, cat: "geo",      text: "L'île de Bouvet en Antarctique est l'endroit le plus isolé du monde : le point habité le plus proche est à 1 700 km." },
  { id: 178, cat: "art",      text: "Le poème le plus court de la langue française est « Va » — un seul mot, utilisé comme impératif dans plusieurs œuvres symbolistes." },
  { id: 179, cat: "tech",     text: "Le premier brevet déposé dans l'histoire des États-Unis concernait une méthode de production de potasse, le 31 juillet 1790." },
  { id: 180, cat: "nature",   text: "Les piranhas, malgré leur réputation féroce, sont majoritairement herbivores — seules quelques espèces sur 60 sont carnivores." },
  { id: 181, cat: "science",  text: "Le papillon monarque migre chaque année sur 4 000 km sans jamais avoir fait le trajet auparavant — guidé par un sens magnétique encore mystérieux." },
  { id: 182, cat: "histoire", text: "La Révolution française a duré 10 ans (1789-1799) et a donné naissance au droit moderne, aux droits de l'homme et au système métrique." },
  { id: 183, cat: "geo",      text: "Le lac Baïkal en Sibérie contient 20 % de toute l'eau douce non gelée de la planète, et a 25 millions d'années." },
  { id: 184, cat: "art",      text: "Rembrandt a réalisé plus de 80 autoportraits tout au long de sa vie, formant une chronique visuelle unique de son vieillissement." },
  { id: 185, cat: "tech",     text: "La médecine moderne utilise des algorithmes d'intelligence artificielle capables de détecter certains cancers mieux que des radiologues humains." },
  { id: 186, cat: "nature",   text: "Les pieuvres ont trois cœurs, neuf cerveaux et un sang bleu — elles sont parmi les animaux les plus étranges de la planète." },
  { id: 187, cat: "science",  text: "Un trou noir de la taille d'une pièce de monnaie contiendrait la masse de la Terre entière compressée en un espace infinitésimal." },
  { id: 188, cat: "histoire", text: "L'ancêtre du bateau à vapeur, inventé par Denis Papin en 1704, fut détruit par des bateliers qui craignaient de perdre leur emploi." },
  { id: 189, cat: "geo",      text: "Plus de 50 % de la population mondiale vit à moins de 60 km d'une côte maritime." },
  { id: 190, cat: "art",      text: "La première édition de Don Quichotte de Cervantes en 1605 est considérée comme le premier roman moderne de la littérature occidentale." },
  { id: 191, cat: "tech",     text: "Les semi-conducteurs en silicium font fonctionner toute notre économie numérique — et le sable des plages en est la matière première." },
  { id: 192, cat: "nature",   text: "Les corbeaux sont capables de reconnaître les visages humains, de s'en souvenir des années et de transmettre cette information à leurs congénères." },
  { id: 193, cat: "science",  text: "Chaque atome de ton corps a déjà fait partie d'une étoile — nous sommes littéralement faits de poussière d'étoiles." },
  { id: 194, cat: "histoire", text: "Le premier hebdomadaire imprimé de l'histoire est le « Relation », publié à Strasbourg en 1609 — ancêtre de tous les journaux modernes." },
  { id: 195, cat: "geo",      text: "Le détroit de Béring séparant l'Asie de l'Amérique fait à son point le plus étroit seulement 82 km — visible à l'œil nu par temps clair." },
  { id: 196, cat: "art",      text: "Le carnaval de Venise existe depuis 1268 — c'est l'un des festivals les plus anciens et les plus célèbres du monde." },
  { id: 197, cat: "tech",     text: "Le premier ordinateur portable commercialisé, l'Osborne 1 en 1981, pesait 11 kg et avait un écran de 5 pouces — mais il révolutionna le monde des affaires." },
  { id: 198, cat: "nature",   text: "Le varan de Komodo peut détecter une odeur à 9 km de distance grâce à sa langue bifide qui analyse les particules dans l'air." },
  { id: 199, cat: "science",  text: "L'espace entre le Soleil et la Terre pourrait contenir 1,3 million de planètes de la taille de la Terre, alignées côte à côte." },
  { id: 200, cat: "histoire", text: "Le drapeau français tricolore a inspiré directement les drapeaux de plus de 50 pays dans le monde, de l'Italie à la Roumanie en passant par le Mexique." },
];

export const CATEGORIES = {
  science:  { label: "Sciences",      emoji: "🔬", color: "#00d4ff" },
  histoire: { label: "Histoire",      emoji: "🏛",  color: "#ffb347" },
  geo:      { label: "Géographie",    emoji: "🌍", color: "#77dd77" },
  art:      { label: "Art & Culture", emoji: "🎨", color: "#ff6eb4" },
  tech:     { label: "Technologie",   emoji: "💻", color: "#b39ddb" },
  nature:   { label: "Nature",        emoji: "🌿", color: "#69c97a" },
};

/**
 * Retourne une anecdote aléatoire parmi les catégories actives,
 * en évitant les IDs récents.
 */
export function getRandomFact(activeCats, recentIds = []) {
  let pool = FACTS.filter(f => activeCats.includes(f.cat));
  // Evite les répétitions récentes si le pool est assez grand
  const filtered = pool.filter(f => !recentIds.includes(f.id));
  if (filtered.length > 0) pool = filtered;
  return pool[Math.floor(Math.random() * pool.length)];
}
